"""Actualizar estructura

Revision ID: 1466226edb5c
Revises: 4bfdba4d0c7b
Create Date: 2021-12-16 19:52:50.980701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1466226edb5c'
down_revision = '4bfdba4d0c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
